#docker exec chromadb ls /usr/bin

services:

  backend:
    build:
      context: ./rag-fastapi
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./rag-fastapi/.env
    networks:
      - rag_network
    
  frontend:
    build:
      context: ./rag-fastapi-frontend

    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - rag_network
    depends_on:
      - backend
  

volumes:
  chroma_data:

networks:
  rag_network:
    driver: bridge